[platformio]
default_envs = esp32-s3-n16r8v
boards_dir = boards

[common]
framework = arduino
platform = espressif32
lib_deps =
    heman/AsyncMqttClient-esphome@^2.1.0
    bblanchon/ArduinoJson@7.4.2
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit NeoPixel@^1.12.3

[env:esp32-s3-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
lib_deps = ${common.lib_deps}
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ESP_DRIVER_TSENS_ENABLE=y
extra_scripts = build_validate.py, ota_flags.py, post_upload.py

[env:esp32-s3-n16r8v-ota]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
lib_deps = ${common.lib_deps}
upload_protocol = espota
upload_port = huawei-sniffer.local
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ESP_DRIVER_TSENS_ENABLE=y
extra_scripts = build_validate.py, ota_flags.py, post_upload.py
